export const PRODUCT_SERVICE = 'PRODUCT_SERVICE';
export const ORDER_SERVICE = 'ORDER_SERVICE';
export const CUSTOMIZATION_SERVICE = 'CUSTOMIZATION_SERVICE';

export const NATS_SERVICE = 'NATS_SERVICE';
